export default [{
  name: 'Frontend Dev. stream 03',
  date: '22 Jun 2021',
  duration: 31,
  interns: 20,
  mentor: 'Igor Bariev',
  lead: 'Mark Ovchinnikov',
  status: 'Oncoming',
},
{
  name: 'C++ Dev. stream 08',
  date: '01 Jun 2021',
  duration: 15,
  interns: 18,
  mentor: 'Anastasia Marchenko',
  lead: 'Maxim Osipenko',
  status: 'Active',
},
{
  name: 'QA stream 02',
  date: '31 May 2021',
  duration: 31,
  interns: 24,
  mentor: 'Maxim Osipenko',
  lead: 'Anatoly Simonov',
  status: 'Paused',
},
{
  name: 'C++ Dev. stream 08',
  date: '01 Jun 2021',
  duration: 15,
  interns: 18,
  mentor: 'Anastasia Marchenko',
  lead: 'Maxim Osipenko',
  status: 'Active',
},
{
  name: 'C++ Dev. stream 08',
  date: '01 Jun 2021',
  duration: 15,
  interns: 18,
  mentor: 'Anastasia Marchenko',
  lead: 'Maxim Osipenko',
  status: 'Active',
},
{
  name: 'Frontend Dev. stream 03',
  date: '22 Jun 2021',
  duration: 31,
  interns: 20,
  mentor: 'Igor Bariev',
  lead: 'Mark Ovchinnikov',
  status: 'Oncoming',
},
{
  name: 'C++ Dev. stream 08',
  date: '01 Jun 2021',
  duration: 15,
  interns: 18,
  mentor: 'Anastasia Marchenko',
  lead: 'Maxim Osipenko',
  status: 'Active',
},
];
