import img1 from '../assets/images/img1.png';
import img2 from '../assets/images/img2.png';
import img3 from '../assets/images/img3.png';
import img4 from '../assets/images/img4.png';

export default [
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    mentorAvatar: img1,
    lead: 'Mark Ovchinnikov',
    leadAvatar: img3,
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    mentorAvatar: img1,
    lead: 'Mark Ovchinnikov',
    leadAvatar: img3,
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    mentorAvatar: img1,
    lead: 'Mark Ovchinnikov',
    leadAvatar: img3,
    status: 'Oncoming',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    mentorAvatar: img1,
    lead: 'Mark Ovchinnikov',
    leadAvatar: img3,
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    mentorAvatar: img1,
    lead: 'Mark Ovchinnikov',
    leadAvatar: img3,
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    mentorAvatar: img2,
    lead: 'Maxim Osipenko',
    leadAvatar: img4,
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    leadAvatar: img4,
    lead: 'Anatoly Simonov',
    mentorAvatar: img1,
    status: 'Paused',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    mentorAvatar: img1,
    lead: 'Mark Ovchinnikov',
    leadAvatar: img3,
    status: 'Oncoming',
  },
];
