export default [
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    lead: 'Anatoly Simonov',
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    lead: 'Anatoly Simonov',
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    lead: 'Anatoly Simonov',
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 05',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 05',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    lead: 'Anatoly Simonov',
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    lead: 'Anatoly Simonov',
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 03',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'QA stream 02',
    date: '31 May 2021',
    duration: 31,
    interns: 24,
    mentor: 'Maxim Osipenko',
    lead: 'Anatoly Simonov',
    status: 'Paused',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 05',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
  {
    title: 'Frontend Dev. stream 05',
    date: '22 Jun 2021',
    duration: 31,
    interns: 20,
    mentor: 'Igor Bariev',
    lead: 'Mark Ovchinnikov',
    status: 'Oncoming',
  },
  {
    title: 'C++ Dev. stream 08',
    date: '01 Jun 2021',
    duration: 15,
    interns: 18,
    mentor: 'Anastasia Marchenko',
    lead: 'Maxim Osipenko',
    status: 'Active',
  },
];
